version: '3'

services:
  web:
    depends_on:
      - db
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      - database__client=mysql
      - database__connection__database=ghost
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=root
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
